// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PfSsl4hrKFdlcrQVXjqH_h6i7fgCJps',
    appId: '1:819030506862:web:8bac511663fe14a859157f',
    messagingSenderId: '819030506862',
    projectId: 'myprojectfirebase-2760a',
    authDomain: 'myprojectfirebase-2760a.firebaseapp.com',
    storageBucket: 'myprojectfirebase-2760a.firebasestorage.app',
    measurementId: 'G-QFYE8MMF4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNZB3WAgAWZygkwuW44CUX7ZsJ0t-j2A',
    appId: '1:819030506862:android:7c2929ca12e384ac59157f',
    messagingSenderId: '819030506862',
    projectId: 'myprojectfirebase-2760a',
    storageBucket: 'myprojectfirebase-2760a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUoZRiUdTohJZzmvmJkxec9BZ6c9-Pks',
    appId: '1:819030506862:ios:51cf34c1bd20577959157f',
    messagingSenderId: '819030506862',
    projectId: 'myprojectfirebase-2760a',
    storageBucket: 'myprojectfirebase-2760a.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUoZRiUdTohJZzmvmJkxec9BZ6c9-Pks',
    appId: '1:819030506862:ios:51cf34c1bd20577959157f',
    messagingSenderId: '819030506862',
    projectId: 'myprojectfirebase-2760a',
    storageBucket: 'myprojectfirebase-2760a.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfAUUQJCiYhdoyZ0J4X9L8tHNqLWbMgQ',
    appId: '1:819030506862:web:7316b6e65fa1c33d59157f',
    messagingSenderId: '819030506862',
    projectId: 'myprojectfirebase-2760a',
    authDomain: 'myprojectfirebase-2760a.firebaseapp.com',
    storageBucket: 'myprojectfirebase-2760a.firebasestorage.app',
    measurementId: 'G-05ZPXWM4WJ',
  );
}
