// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwGm2dhcxKQmyllqYx3MoC3fcEHnGuKN0',
    appId: '1:710344379329:web:bb354581748140da6c7d40',
    messagingSenderId: '710344379329',
    projectId: 'gin-firebase-backend-8dcfe',
    authDomain: 'gin-firebase-backend-8dcfe.firebaseapp.com',
    storageBucket: 'gin-firebase-backend-8dcfe.firebasestorage.app',
    measurementId: 'G-3KKXGST8EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRy3S7Z4FyTXuxmGYTzuF-jHqKRWF_Ie4',
    appId: '1:710344379329:android:a005579cc0b8ba8f6c7d40',
    messagingSenderId: '710344379329',
    projectId: 'gin-firebase-backend-8dcfe',
    storageBucket: 'gin-firebase-backend-8dcfe.firebasestorage.app',
  );
}
